version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    target-branch: develop
    open-pull-requests-limit: 5
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "@angular-eslint/*"
        update-types:
          - minor
          - patch
      npm-minor-patch:
        patterns:
          - "*"
        exclude-patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "@angular-eslint/*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: chore(deps)
