version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        BUILD_FOLDER: "dist"
phases:
    install:
        runtime-versions:
            nodejs: 18
        commands:
            - echo Installing source NPM dependencies...
            - npm config set legacy-peer-deps true
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started for ${CURRENT_ENVIRONMENT}
            - ng build --configuration ${CURRENT_ENVIRONMENT}
    post_build:
        commands:
            - cp -R node_modules/ dist/node_modules
artifacts:
    files:
        - "**/*"
